Fix travis build.
It's broken with this error:
Error: No implementations provided for the following modules:
         Big_int referenced from prime_factors.cmx
This looks like a problem in Core which this commit works around
by using float rather than BigInt (we just need to do a sqrt of an
Int64).